### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by bpmweel**
- Repo structure changed to src and test folder.
- Integrated Testing and Main building CMakeLists.txt files.
   Main CMakeLists.txt file in root now builds both sub-directories, each sub-directory has its own CMakeLists.txt file to specify just the sources and linking needed for that sub-project.
- Merged feature/ci branch here to include automated building using github actions

### CODE REVIEW

**Comment by pushpanjalip** [comment]
It works fine for me. 
I was confused about CMake files inside src & test but after reading description in PR. I got it.

**Comment by pushpanjalip** [comment]
@bpmweel  I don't know if restructuring is causing the issue or something  else but if I try to add new Qt Designer form class. The files that are created end up at different places. Please refer to the image below

Screenshot 2021-03-15 at 20 24 58

**Review by geek-yang — DISMISSED** [review]
Looks good to me! And it works on my machine without errors.

**Comment by kretep** [comment]
Works fine for me also. The only thing that confused me a bit is that the compiled executable ends up in build/src/

**Review by kretep — DISMISSED** [review]

**Pull request merged**
